name: DeepThought
version: "1.0.8"
license: "GPL-2.0-or-later"
date: 2025-01-03
description: |
    This package provides functions for computations in finitely generated nilpotent groups based on the Deep Thought algorithm.

authors:
    - name: Nina Wagner
      url: mailto:github@n-i-n-a.de

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">= 4.12"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "polycyclic"
      version: ">= 2.11"
      url: "https://gap-packages.github.io/polycyclic/"

www: https://gap-packages.github.io/DeepThought/
readme: README.md
packageinfo: https://gap-packages.github.io/DeepThought/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/DeepThought/releases/download/v1.0.8/DeepThought-1.0.8.tar.gz

abstract: |
    This package provides functions for computations in finitely generated nilpotent groups based on the Deep Thought algorithm.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    Deep Thought, finitely generated nilpotent groups, Hall polynomials.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>WH25</span>]   <b class='BibAuthor'>Wagner, N. and Horn, M.</b>,
     <i class='BibTitle'>DeepThought, This package provides functions for computations in finitely generated nilpotent groups based on the Deep Thought algorithm.,
             Version 1.0.8</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/DeepThought/">https://gap-packages.github.io/DeepThought/</a></span>.
    </p>
    

bibtex: |
    @misc{ DeepThought,
      author =           {Wagner, N. and Horn, M.},
      title =            {{DeepThought},  {This  package  provides functions for
                          computations  in  finitely  generated nilpotent groups
                          based on the Deep Thought algorithm.}, {V}ersion 1.0.8},
      month =            {Jan},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href    {https://gap-packages.github.io/DeepThought/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{DeepThought/}}},
      keywords =         {Deep  Thought;  finitely  generated  nilpotent groups;
                          Hall polynomials},
      printedkey =       {WH25}
    }

