name: DeepThought
version: 1.0.6
date: 2022-10-06
description: |
    This package provides functions for computations in finitely generated nilpotent groups based on the Deep Thought algorithm.

authors:
    - name: Nina Wagner
      url: mailto:github@n-i-n-a.de

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">= 4.9"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "polycyclic"
      version: ">= 2.11"
      url: "https://gap-packages.github.io/polycyclic/"

www: https://gap-packages.github.io/DeepThought/
readme: README.md
packageinfo: https://gap-packages.github.io/DeepThought/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/DeepThought/releases/download/v1.0.6/DeepThought-1.0.6.tar.gz

abstract: |
    This package provides functions for computations in finitely generated nilpotent groups based on the Deep Thought algorithm.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
